
name: Upload to GCS

on:
  push:
    branches: [ "main" ]
jobs:

  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.7.3
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      - name: Cloud Storage Uploader
        uses: google-github-actions/upload-cloud-storage@v0.10.2
        with:
          path: './'
          destination: 'static.resizely.io/docs'
          glob: '**/*.md'
